name: Build and Deploy
run-name: Workflow run for ${{ github.ref }}
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      aws-deploy:
        type: boolean
        required: true
        default: false
jobs:
  build-api-service-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfilebuild
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/aml-authoring-tool:${{ github.ref_name }}
          build-args: |
            VITE_REACT_APP_ENV=develop
            VITE_SENTRY_DSN=${{ secrets.SENTRY_DSN }}
